### ISSUE TITLE
[SUGGESTION] Option to only hide Turbo/Prime badge but still show Sub badges

### ISSUE THREAD

**Issue by hobbldygoop** [chatty/chatty#105]
Currently you only have the choice of either showing all Usericons or showing none at all. 

With a lot of people having Twitch Prime nowadays and the blue badge standing out quite a lot this can become very distracting, but I still want to see who's a sub, it would be nice to have an option to only show the sub badges or not show the prime badges.

**Comment by tduva** [comment]
Add a Custom Usericon of type Turbo and simply select no image. Same for Prime. Make sure Custom Usericons are enabled on the checkbox.

**Comment by hobbldygoop** [comment]
Yeah I tried that but I kept getting an error and it didn't let me set it, I even had to restart a few times cause every time I tried going into the settings the error popped up again and I couldn't do anything.

```
Error Report // Chatty Version 0.8.4.1 / JDK8 / Java: 1.8.0_66 (Oracle Corporation) OS: Mac OS X (10.11.6/x86_64) / [Memory] total: 508,928 used: 150,643 free: 358,284 max: 7,456,768 [Uptime] 32s

01:47:03 GOT (200, 2071, gzip): https://api.twitch.tv/kraken/streams/valkia
01:47:03 GET (v3): https://badges.twitch.tv/v1/badges/channels/3481156/display?language=en
01:47:03 GOT (200, 1362, gzip): https://api.twitch.tv/kraken/channels/valkia
01:47:04 GOT (200, 1043): https://badges.twitch.tv/v1/badges/channels/3481156/display?language=en
01:47:07 Unhandled Exception:
java.lang.NullPointerException
	at chatty.gui.components.settings.UsericonEditor$ImageRenderer.setValue(UsericonEditor.java:193)
	at javax.swing.table.DefaultTableCellRenderer.getTableCellRendererComponent(DefaultTableCellRenderer.java:257)
	at javax.swing.JTable$AccessibleJTable.getAccessibleChild(JTable.java:7031)
	at javax.swing.JTable$AccessibleJTable.getAccessibleAt(JTable.java:7418)
	at javax.swing.JTable$AccessibleJTable.valueChanged(JTable.java:6932)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:164)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:211)
	at javax.swing.DefaultListSelectionModel.setLeadSelectionIndex(DefaultListSelectionModel.java:815)
	at javax.swing.JTable.clearSelectionAndLeadAnchor(JTable.java:2128)
	at javax.swing.JTable.tableChanged(JTable.java:4445)
	at javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:296)
	at javax.swing.table.AbstractTableModel.fireTableDataChanged(AbstractTableModel.java:198)
	at chatty.gui.components.settings.ListTableModel.setData(ListTableModel.java:37)
	at chatty.gui.components.settings.TableEditor.setData(TableEditor.java:277)
	at chatty.gui.components.settings.ImageSettings.setData(ImageSettings.java:63)
	at chatty.gui.components.settings.SettingsDialog.loadSettings(SettingsDialog.java:326)
	at chatty.gui.components.settings.SettingsDialog.showSettings(SettingsDialog.java:272)
	at chatty.gui.components.settings.SettingsDialog.showSettings(SettingsDialog.java:268)
	at chatty.gui.MainGui$MainMenuListener.actionPerformed(MainGui.java:1291)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.menuDragMouseReleased(BasicMenuItemUI.java:943)
	at javax.swing.JMenuItem.fireMenuDragMouseReleased(JMenuItem.java:586)
	at javax.swing.JMenuItem.processMenuDragMouseEvent(JMenuItem.java:483)
	at javax.swing.JMenuItem.processMouseEvent(JMenuItem.java:429)
	at javax.swing.MenuSelectionManager.processMouseEvent(MenuSelectionManager.java:329)
	at javax.swing.plaf.basic.BasicPopupMenuUI$MouseGrabber.eventDispatched(BasicPopupMenuUI.java:870)
	at java.awt.Toolkit$SelectiveAWTEventListener.eventDispatched(Toolkit.java:2425)
	at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2317)
	at java.awt.Toolkit.notifyAWTEventListeners(Toolkit.java:2275)
	at java.awt.Component.dispatchEventImpl(Component.java:4787)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

That's just after adding two new Usericon things with Prime and Turbo selected, everything else left empty.

**Comment by tduva** [comment]
Can you tell me what `/get customUsericons` returns.

Either way, there is no reason it should fail there. I've added many Usericons in different configurations and never had that. It's possible that it's a Java bug similiar to the one I encountered with the list renderer before.

**Comment by hobbldygoop** [comment]
```[03:26] Setting 'customUsericons' is '[[10,"","","",null], [1,"","","",null]]'.```

k I'll try updating my java, thx

**Comment by hobbldygoop** [comment]
yeah never mind works now with updated java, seems it was defaulting to some weird JDK I apparently installed some time ago, sorry about wasting your time, thanks for the help!
