### ISSUE TITLE
Limit Chatty Memory Usage

### ISSUE THREAD

**Issue by mtcjayne** [chatty/chatty#207]
How do I limit Chatty's memory usage on the version labeled "With global hotkey support (Windows only):"?

Changing the shortcut to "javaw -jar path/to/Chatty.jar" and adding the documented Java flag "-Xmx" as "-Xmx250M" just leaves Chatty literally using as much of my CPU as it can latch onto and never actually showing a window.

**Comment by mtcjayne** [comment]
`[2017-11-26 21:42:50 INFO] ### Log start (2017-11-26 21:42:50 -0600) [chatty.TwitchClient/<init>]
[2017-11-26 21:42:50 INFO] Chatty Version 0.8.7 Hotkey / JDK8 [chatty.TwitchClient/<init>]
[2017-11-26 21:42:50 INFO] Java: 1.8.0_141 (Oracle Corporation) OS: Windows 10 (10.0/amd64) [chatty.TwitchClient/<init>]
[2017-11-26 21:42:50 INFO] [Working Directory] D:\Users\mtcjayne\Downloads\Chatty_0.8.7_hotkey_64bit [Settings Directory] D:\Users\mtcjayne\Downloads\Chatty_0.8.7_hotkey_64bit\ [Classpath] D:\Users\mtcjayne\Downloads\Chatty_0.8.7_hotkey_64bit\Chatty.jar [chatty.TwitchClient/<init>]
[2017-11-26 21:42:50 INFO] Retina Display: false [chatty.TwitchClient/<init>]
[2017-11-26 21:42:50 INFO] GET (v5): https://api.twitch.tv/kraken/communities/top?limit=100 [chatty.util.api.TwitchApiRequest/getUrl]
[2017-11-26 21:42:50 INFO] Loading settings from file: D:\Users\mtcjayne\Downloads\Chatty_0.8.7_hotkey_64bit\settings [chatty.util.settings.Settings/loadSettingsFromJson]
[2017-11-26 21:42:50 INFO] Loading settings from file: D:\Users\mtcjayne\Downloads\Chatty_0.8.7_hotkey_64bit\login [chatty.util.settings.Settings/loadSettingsFromJson]
[2017-11-26 21:42:50 INFO] Loading settings from file: D:\Users\mtcjayne\Downloads\Chatty_0.8.7_hotkey_64bit\favoritesAndHistory [chatty.util.settings.Settings/loadSettingsFromJson]
[2017-11-26 21:42:50 INFO] Loading settings from file: D:\Users\mtcjayne\Downloads\Chatty_0.8.7_hotkey_64bit\statusPresets [chatty.util.settings.Settings/loadSettingsFromJson]
[2017-11-26 21:42:50 INFO] Settings: server:, port:, serverDefault:irc.chat.twitch.tv, portDefault:6697,6667,443,80, membershipEnabled:true, whisperEnabled:true, groupChatServer:, groupChatPort:, imageCache:true, dontSaveSettings:false, usePassword:false, debugLogIrc:false, showJoinsParts:false, saveChannelHistory:true, historyClear:true, autoScroll:true, bufferSize:500 [chatty.SettingsManager/debugSettings]
[2017-11-26 21:42:50 INFO] Usericons: Loaded 0/0 [chatty.util.api.usericons.UsericonManager/loadFromSettings]
[2017-11-26 21:42:50 INFO] Read 0 addressbook entries from D:\Users\mtcjayne\Downloads\Chatty_0.8.7_hotkey_64bit\addressbook [chatty.Addressbook/loadFromFile]
[2017-11-26 21:42:50 INFO] StatusPresets: Loaded 0/0 entries. [chatty.gui.components.admin.StatusHistory/loadFromSettings]
[2017-11-26 21:42:50 INFO] Drawing settings: d3d: false / noddraw: true [chatty.TwitchClient/initDxSettings]
[2017-11-26 21:42:50 INFO] Setting LAF to javax.swing.plaf.metal.MetalLookAndFeel [chatty.gui.GuiUtil/setLookAndFeel]
[2017-11-26 21:42:50 INFO] Create GUI.. [chatty.TwitchClient/<init>]
[2017-11-26 21:42:51 INFO] GOT (200, 27024, gzip): https://api.twitch.tv/kraken/communities/top?limit=100 [chatty.util.api.Requests$1/requestResult]
[2017-11-26 21:42:52 INFO] GET (v5): https://api.twitch.tv/kraken/streams/followed?limit=100&offset=0 (using authorization) [chatty.util.api.TwitchApiRequest/getUrl]
[2017-11-26 21:42:52 INFO] Cache: Trying to load Emoticons.. [chatty.util.SimpleCache/load]
[2017-11-26 21:42:52 INFO] GOT (200, 2618, gzip): https://api.twitch.tv/kraken/streams/followed?limit=100&offset=0 (using authorization) [chatty.util.api.Requests$1/requestResult]
[2017-11-26 21:42:52 INFO] Got 2 (limit: 100) followed streams. [chatty.util.api.StreamInfoManager/requestResultFollows]
[2017-11-26 21:43:00 INFO] [Memory] total: 227,840 used: 191,705 free: 36,134 max: 227,840 [Uptime] 10s [chatty.util.LogUtil/logMemoryUsage]`

With an ultimate crash showing a dialog box containing

`Error Report // 2017-11-26 21:43:34 -0600 / Chatty Version 0.8.7 Hotkey / JDK8 / Java: 1.8.0_141 (Oracle Corporation) OS: Windows 10 (10.0/amd64) / [Memory] total: 227,840 used: 24,086 free: 203,753 max: 227,840 [Uptime] 43s

21:42:52 Cache: Trying to load Emoticons..
21:42:52 GOT (200, 2618, gzip): https://api.twitch.tv/kraken/streams/followed?limit=100&offset=0 (using authorization)
21:42:52 Got 2 (limit: 100) followed streams.
21:43:00 [Memory] total: 227,840 used: 191,705 free: 36,134 max: 227,840 [Uptime] 10s
21:43:33 Unhandled Exception:
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.regex.Pattern$BnM.optimize(Unknown Source)
	at java.util.regex.Pattern.compile(Unknown Source)
	at java.util.regex.Pattern.<init>(Unknown Source)
	at java.util.regex.Pattern.compile(Unknown Source)
	at java.lang.String.replace(Unknown Source)
	at chatty.util.api.Emoticon.<init>(Emoticon.java:273)
	at chatty.util.api.Emoticon$Builder.build(Emoticon.java:215)
	at chatty.util.api.EmoticonManager.parseEmoticon(EmoticonManager.java:150)
	at chatty.util.api.EmoticonManager.parseEmoticons(EmoticonManager.java:65)
	at chatty.util.api.EmoticonManager.handleData(EmoticonManager.java:38)
	at chatty.util.api.CachedManager.load(CachedManager.java:54)
	at chatty.util.api.TwitchApi.requestEmoticons(TwitchApi.java:86)
	at chatty.gui.MainGui.createGui(MainGui.java:297)
	at chatty.gui.MainGui.run(MainGui.java:172)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

`

**Comment by tduva** [comment]
That's not enough memory to load and store the metadata for over 280k emotes. You need to increase it or use the latest beta, which doesn't load all the emotes at once anymore (which used to be ok before everyone got Affiliate emotes).
