### ISSUE TITLE
NPE on 9.1 start

### ISSUE THREAD

**Issue by anibyl** [chatty/chatty#253]
Swing components call `getName` when `room` is not initialized.

```
Error Report // 2018-04-13 17:51:15 +0300 / Chatty Version 0.9.1 / JDK8 / Java: 1.8.0_162 (Oracle Corporation) OS: Linux (4.13.0-38-generic/amd64) / [Memory] total: 197 632 used: 47 918 free: 149 713 max: 3 624 960 [Uptime] 4s

17:51:11 Drawing settings: d3d: false / noddraw: false
17:51:11 [LAF] Set system/Default [com.sun.java.swing.plaf.gtk.GTKLookAndFeel]
17:51:11 Create GUI..
17:51:12 GOT (200, 26709, gzip): https://api.twitch.tv/kraken/communities/top?limit=100
17:51:15 Unhandled Exception:
java.lang.NullPointerException
	at chatty.gui.components.Channel.getName(Channel.java:201)
	at com.sun.java.swing.plaf.gtk.GTKStyle.getInsets(GTKStyle.java:316)
	at javax.swing.plaf.synth.SynthStyle.installDefaults(SynthStyle.java:913)
	at javax.swing.plaf.synth.SynthLookAndFeel.updateStyle(SynthLookAndFeel.java:265)
	at javax.swing.plaf.synth.SynthPanelUI.updateStyle(SynthPanelUI.java:117)
	at javax.swing.plaf.synth.SynthPanelUI.installDefaults(SynthPanelUI.java:100)
	at javax.swing.plaf.basic.BasicPanelUI.installUI(BasicPanelUI.java:56)
	at javax.swing.plaf.synth.SynthPanelUI.installUI(SynthPanelUI.java:62)
	at javax.swing.JComponent.setUI(JComponent.java:666)
	at javax.swing.JPanel.setUI(JPanel.java:153)
	at javax.swing.JPanel.updateUI(JPanel.java:126)
	at javax.swing.JPanel.<init>(JPanel.java:86)
	at javax.swing.JPanel.<init>(JPanel.java:109)
	at javax.swing.JPanel.<init>(JPanel.java:117)
	at chatty.gui.components.Channel.<init>(Channel.java:76)
	at chatty.gui.Channels.createChannel(Channels.java:194)
	at chatty.gui.Channels.addDefaultChannel(Channels.java:189)
	at chatty.gui.Channels.<init>(Channels.java:93)
	at chatty.gui.MainGui.createGui(MainGui.java:282)
	at chatty.gui.MainGui.run(MainGui.java:180)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by tduva** [comment]
I just noticed it happened to be in the debug excerpt: `[LAF] Set system/Default [com.sun.java.swing.plaf.gtk.GTKLookAndFeel]` D:

It doesn't happen for me on Windows, so I guess it's specific to the `GTKLookAndFeel`. Either way, I merged your PR so hopefully it should be fixed now. Thanks.

**Comment by anibyl** [comment]
Hopefully `GTKStyle` doesn't use any other getters with `room.` on instance creation.
Thanks for merging.

**Comment by anibyl** [comment]
I think it can be closed.
