### ISSUE TITLE
Fedora 28 error with java.awt.HeadlessException with OpenJDK 1.8

### ISSUE THREAD

**Issue by predatorian3** [chatty/chatty#261]
Fedora 28 using OpenJDK 1.8 seems to have a problem with `java.awt.HeadlessException`. Chatty will get to the end of the output, and hang, but no window shows.

OpenJDK Version

```bash
[predatorian@localhost Chatty_0.9.1]$ java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-b10)
OpenJDK 64-Bit Server VM (build 25.171-b10, mixed mode)
```

Operating System Version

```bash
[predatorian@localhost Chatty_0.9.1]$ uname -a
Linux localhost.localdomain 4.16.9-300.fc28.x86_64 #1 SMP Thu May 17 06:39:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
Chatty 0.9.1 Error

```java
[predatorian@localhost Chatty_0.9.1]$ java -jar Chatty.jar 
[2018-05-25 18:06:04 INFO] ### Log start (2018-05-25 18:06:04 -0500) [chatty.TwitchClient/<init>]
[2018-05-25 18:06:04 INFO] Chatty Version 0.9.1 / JDK8 [chatty.TwitchClient/<init>]
[2018-05-25 18:06:04 INFO] Java: 1.8.0_171 (Oracle Corporation) OS: Linux (4.16.9-300.fc28.x86_64/amd64) [chatty.TwitchClient/<init>]
[2018-05-25 18:06:04 INFO] [Working Directory] /home/predatorian/Downloads/Chatty_0.9.1 [Settings Directory] /home/predatorian/.chatty/ [Classpath] Chatty.jar [chatty.TwitchClient/<init>]
[2018-05-25 18:06:04 INFO] Retina Display: false [chatty.TwitchClient/<init>]
[2018-05-25 18:06:04 INFO] GET (v5): https://api.twitch.tv/kraken/communities/top?limit=100 [chatty.util.api.TwitchApiRequest/getUrl]
[2018-05-25 18:06:04 INFO] Loading settings from file: /home/predatorian/.chatty/settings [chatty.util.settings.Settings/loadSettingsFromJson]
[2018-05-25 18:06:04 WARNING] Error loading settings from file: java.nio.file.NoSuchFileException: /home/predatorian/.chatty/settings [chatty.util.settings.Settings/loadSettingsFromJson]
[2018-05-25 18:06:04 INFO] Loading settings from file: /home/predatorian/.chatty/login [chatty.util.settings.Settings/loadSettingsFromJson]
[2018-05-25 18:06:04 WARNING] Error loading settings from file: java.nio.file.NoSuchFileException: /home/predatorian/.chatty/login [chatty.util.settings.Settings/loadSettingsFromJson]
[2018-05-25 18:06:04 INFO] Loading settings from file: /home/predatorian/.chatty/favoritesAndHistory [chatty.util.settings.Settings/loadSettingsFromJson]
[2018-05-25 18:06:04 WARNING] Error loading settings from file: java.nio.file.NoSuchFileException: /home/predatorian/.chatty/favoritesAndHistory [chatty.util.settings.Settings/loadSettingsFromJson]
[2018-05-25 18:06:04 INFO] Loading settings from file: /home/predatorian/.chatty/statusPresets [chatty.util.settings.Settings/loadSettingsFromJson]
[2018-05-25 18:06:04 WARNING] Error loading settings from file: java.nio.file.NoSuchFileException: /home/predatorian/.chatty/statusPresets [chatty.util.settings.Settings/loadSettingsFromJson]
[2018-05-25 18:06:04 INFO] Migrating Favorites/History [chatty.SettingsManager/overrideSettings]
[2018-05-25 18:06:04 INFO] Overriding hotkey setting: [dialog.streams, ctrl L, 1] [chatty.SettingsManager/overrideHotkeySettings]
[2018-05-25 18:06:04 INFO] Overriding hotkey setting: [dialog.toggleEmotes, ctrl E] [chatty.SettingsManager/overrideHotkeySettings]
[2018-05-25 18:06:04 INFO] Overriding hotkey setting: [dialog.search, ctrl F] [chatty.SettingsManager/overrideHotkeySettings]
[2018-05-25 18:06:04 INFO] Overriding hotkey setting: [dialog.joinChannel, ctrl J] [chatty.SettingsManager/overrideHotkeySettings]
[2018-05-25 18:06:04 INFO] Overriding hotkey setting: [window.toggleUserlist, shift F10, 1] [chatty.SettingsManager/overrideHotkeySettings]
[2018-05-25 18:06:04 INFO] Overriding hotkey setting: [window.toggleInput, ctrl F10, 1] [chatty.SettingsManager/overrideHotkeySettings]
[2018-05-25 18:06:04 INFO] Overriding hotkey setting: [window.toggleCompact, F10, 1] [chatty.SettingsManager/overrideHotkeySettings]
[2018-05-25 18:06:04 INFO] Overriding hotkey setting: [window.toggleCompactMaximized, F11, 1] [chatty.SettingsManager/overrideHotkeySettings]
[2018-05-25 18:06:04 INFO] Overriding hotkey setting: [tabs.close, ctrl W] [chatty.SettingsManager/overrideHotkeySettings]
[2018-05-25 18:06:04 INFO] Overriding hotkey setting: [tabs.next, ctrl TAB, 1] [chatty.SettingsManager/overrideHotkeySettings]
[2018-05-25 18:06:04 INFO] Overriding hotkey setting: [tabs.previous, ctrl shift TAB, 1] [chatty.SettingsManager/overrideHotkeySettings]
[2018-05-25 18:06:04 INFO] Overriding hotkey setting: [selection.toggle, ctrl SPACE] [chatty.SettingsManager/overrideHotkeySettings]
[2018-05-25 18:06:04 INFO] Overriding hotkey setting: [selection.toggle, ctrl S] [chatty.SettingsManager/overrideHotkeySettings]
[2018-05-25 18:06:04 INFO] Overriding hotkey setting: [about, F1, 1] [chatty.SettingsManager/overrideHotkeySettings]
[2018-05-25 18:06:04 INFO] Settings: server:, port:, serverDefault:irc.chat.twitch.tv, portDefault:6697,6667,443,80, membershipEnabled:true, whisperEnabled:false, groupChatServer:, groupChatPort:, imageCache:true, dontSaveSettings:false, usePassword:false, debugLogIrc:false, showJoinsParts:false, saveChannelHistory:true, historyClear:true, autoScroll:true, bufferSize:500 [chatty.SettingsManager/debugSettings]
[2018-05-25 18:06:04 INFO] [Localization] Loaded locale 'en' for requested '' [chatty.lang.Language/setLanguage]
[2018-05-25 18:06:04 WARNING] Error loading emoticon sizes: java.nio.file.NoSuchFileException: /home/predatorian/.chatty/cache/emoticon_sizes [chatty.util.api.EmoticonSizeCache/loadFromFile]
[2018-05-25 18:06:04 INFO] Usericons: Loaded 0/0 [chatty.util.api.usericons.UsericonManager/loadFromSettings]
[2018-05-25 18:06:04 WARNING] Error reading addressbook: java.nio.file.NoSuchFileException: /home/predatorian/.chatty/addressbook [chatty.Addressbook/loadFromFile]
[2018-05-25 18:06:04 INFO] Read 0 addressbook entries from /home/predatorian/.chatty/addressbook [chatty.Addressbook/loadFromFile]
[2018-05-25 18:06:04 INFO] StatusPresets: Loaded 0/0 entries. [chatty.gui.components.admin.StatusHistory/loadFromSettings]
[2018-05-25 18:06:04 INFO] Drawing settings: d3d: false / noddraw: false [chatty.TwitchClient/initDxSettings]
[2018-05-25 18:06:04 INFO] [LAF] Set default/Default [javax.swing.plaf.metal.MetalLookAndFeel] [chatty.gui.LaF/setLookAndFeel]
[2018-05-25 18:06:04 INFO] Create GUI.. [chatty.TwitchClient/<init>]
[2018-05-25 18:06:04 SEVERE] java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.JFrame.<init>(JFrame.java:189)
	at chatty.gui.MainGui.<init>(MainGui.java:172)
	at chatty.TwitchClient.<init>(TwitchClient.java:288)
	at chatty.Chatty.main(Chatty.java:126)
 [chatty.ErrorHandler/uncaughtException]
[2018-05-25 18:06:05 INFO] GOT (200, 27052, gzip): https://api.twitch.tv/kraken/communities/top?limit=100 [chatty.util.api.Requests$1/requestResult]
```

**Comment by predatorian3** [comment]
Solution: https://ask.fedoraproject.org/en/question/102532/headless-java-on-a-desktop/?answer=102533#post-id-102533

Fedora comes with OpenJDK Headless only in an install. So I had to just install `sudo dnf install java-1.8.0-openjdk` and now it worked.
