### ISSUE TITLE
Chatty stopped launching in Ubuntu 18.04 issuing chatty.ErrorHandler/uncaughtException error

### ISSUE THREAD

**Issue by linuxgameconsortium** [chatty/chatty#274]
Chatty does not launch via Twitch GUI. And trying to manually launch the Chatty app via Java produces the output below. Any help would be great.

```
java -jar Chatty.jar 
[2018-08-22 17:47:55 INFO] ### Log start (2018-08-22 17:47:55 -0400) [chatty.TwitchClient/<init>]
[2018-08-22 17:47:55 INFO] Chatty Version 0.9.2b5 / JDK8 [chatty.TwitchClient/<init>]
[2018-08-22 17:47:55 INFO] Java: 10.0.2 (Oracle Corporation / /usr/lib/jvm/java-11-openjdk-amd64) OS: Linux (4.15.0-32-generic/amd64) [chatty.TwitchClient/<init>]
[2018-08-22 17:47:55 INFO] [Working Directory] /opt/Chatty_0.9.2b5 [Settings Directory] /home/todd/.chatty/ [Classpath] Chatty.jar [chatty.TwitchClient/<init>]
[2018-08-22 17:47:55 SEVERE] java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.desktop/java.awt.Toolkit.newAWTError(Toolkit.java:472)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:488)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1608)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:532)
	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:613)
	at chatty.gui.GuiUtil.hasRetinaDisplay(GuiUtil.java:299)
	at chatty.TwitchClient.<init>(TwitchClient.java:191)
	at chatty.Chatty.main(Chatty.java:132)
Caused by: java.lang.ClassNotFoundException: org.GNOME.Accessibility.AtkWrapper
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:485)
	... 14 more
 [chatty.ErrorHandler/uncaughtException]
```

**Comment by nuubmuffinz** [comment]
This seems to be a linux only issue regarding openjdk-11, it works great with openjdk-8. I ran "java -jar chatty.jar" with openjdk-11 and got the error. I uninstalled 11 and installed openjdk-8 and ran the same command and it ran perfectly.
