### ISSUE TITLE
Ошибка связана с chat notifications: 

### ISSUE THREAD

**Issue by sergservis** [chatty/chatty#395]
[02:16:15 WARN]: [Chatty] Task #34810 for Chatty v2.19-SNAPSHOT generated an exception
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError:
        at ru.mrbrikster.chatty.notifications.ChatNotification.run(ChatNotification.java:65) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NoClassDefFoundError:
        ... 8 more

**Comment by tduva** [comment]
This isn't the Chatty you're looking for, this is a Twitch Chat Client, not Minecraft related.

**Comment by sergservis** [comment]
excuse me
