### ISSUE TITLE
Look and Feel

### ISSUE THREAD

**Issue by pyro17** [chatty/chatty#43]
Setting it to "System" causes a NullPointerException and can only be recovered by changing the look&feel in the setting file manually to default.

using Windows 10

**Comment by tduva** [comment]
I need more information like the full error message, otherwise I can't Google the error and make an educated guess on how to fix it, since I don't have access to Windows 10 myself.

**Comment by pyro17** [comment]
Here it is:

Error Report // Chatty Version 0.8.1 / Java: 1.8.0_77 (Oracle Corporation) OS: Windows 10 (10.0/x86) / [Memory] total: 71.720 used: 64.870 free: 6.849 max: 253.440 [Uptime] 51s

15:10:04 Cache: Saved emoticons.
15:10:04 Added 47967 emotes. Now 8156 emotesets and 0 channels with exclusive emotes (163 global emotes).
15:10:07 [Memory] total: 71.720 used: 55.011 free: 16.708 max: 253.440 [Uptime] 11s
15:10:47 Setting LAF to com.sun.java.swing.plaf.windows.WindowsLookAndFeel
15:10:47 Unhandled Exception:
java.lang.NullPointerException
	at com.sun.java.swing.plaf.windows.XPStyle.getTypeEnumName(Unknown Source)
	at com.sun.java.swing.plaf.windows.XPStyle.getBorder(Unknown Source)
	at com.sun.java.swing.plaf.windows.WindowsLookAndFeel$XPBorderValue.getXPValue(Unknown Source)
	at com.sun.java.swing.plaf.windows.WindowsLookAndFeel$XPValue.createValue(Unknown Source)
	at javax.swing.UIDefaults.getFromHashtable(Unknown Source)
	at javax.swing.UIDefaults.get(Unknown Source)
	at javax.swing.MultiUIDefaults.get(Unknown Source)
	at javax.swing.UIDefaults.getBorder(Unknown Source)
	at javax.swing.UIManager.getBorder(Unknown Source)
	at javax.swing.border.TitledBorder.getBorder(Unknown Source)
	at javax.swing.border.TitledBorder.getBorderInsets(Unknown Source)
	at javax.swing.border.AbstractBorder.getBorderInsets(Unknown Source)
	at javax.swing.JComponent.getInsets(Unknown Source)
	at java.awt.FlowLayout.preferredLayoutSize(Unknown Source)
	at java.awt.Container.preferredSize(Unknown Source)
	at java.awt.Container.getPreferredSize(Unknown Source)
	at javax.swing.JComponent.getPreferredSize(Unknown Source)
	at java.awt.GridBagLayout.GetLayoutInfo(Unknown Source)
	at java.awt.GridBagLayout.getLayoutInfo(Unknown Source)
	at java.awt.GridBagLayout.ArrangeGrid(Unknown Source)
	at java.awt.GridBagLayout.arrangeGrid(Unknown Source)
	at java.awt.GridBagLayout.layoutContainer(Unknown Source)
	at java.awt.Container.layout(Unknown Source)
	at java.awt.Container.doLayout(Unknown Source)
	at java.awt.Container.validateTree(Unknown Source)
	at java.awt.Container.validateTree(Unknown Source)
	at java.awt.Container.validateTree(Unknown Source)
	at java.awt.Container.validateTree(Unknown Source)
	at java.awt.Container.validate(Unknown Source)
	at javax.swing.SwingUtilities.updateComponentTreeUI(Unknown Source)
	at chatty.gui.GuiUtil.updateLookAndFeel(GuiUtil.java:250)
	at chatty.gui.GuiUtil.updateLookAndFeel(GuiUtil.java:248)
	at chatty.gui.GuiUtil.updateLookAndFeel(GuiUtil.java:248)
	at chatty.gui.GuiUtil.updateLookAndFeel(GuiUtil.java:242)
	at chatty.gui.MainGui$MySettingChangeListener.settingChangedInternal(MainGui.java:3600)
	at chatty.gui.MainGui$MySettingChangeListener.settingChanged(MainGui.java:3542)
	at chatty.util.settings.Settings.settingChanged(Settings.java:57)
	at chatty.util.settings.Settings.set(Settings.java:234)
	at chatty.util.settings.Settings.setString(Settings.java:180)
	at chatty.gui.components.settings.SettingsDialog.saveStringSettings(SettingsDialog.java:403)
	at chatty.gui.components.settings.SettingsDialog.saveSettings(SettingsDialog.java:372)
	at chatty.gui.components.settings.SettingsDialog.save(SettingsDialog.java:688)
	at chatty.gui.components.settings.SettingsDialog.actionPerformed(SettingsDialog.java:680)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.awt.Dialog.show(Unknown Source)
	at java.awt.Component.show(Unknown Source)
	at java.awt.Component.setVisible(Unknown Source)
	at java.awt.Window.setVisible(Unknown Source)
	at java.awt.Dialog.setVisible(Unknown Source)
	at chatty.gui.components.settings.SettingsDialog.showSettings(SettingsDialog.java:275)
	at chatty.gui.components.settings.SettingsDialog.showSettings(SettingsDialog.java:260)
	at chatty.gui.MainGui$MainMenuListener.actionPerformed(MainGui.java:1226)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by lewisje** [comment]
I'm not sure why you would even want to set it to "System": It's a garish old bitmap font. (If you're accustomed to the Mac, "System" is a placeholder for the OS system font, rather than a specific legacy font as in Windows.)

**Comment by pyro17** [comment]
Look&Feel is not for the font directly. It is for the style of the programm. AWT and Swing both come with a different java specific style.

So setting the look and feel to system means that the programm will look like a regular Windows / Linux programm since it uses that style. 

Also if it is something you do not want, thats fine. But an option that makes the programm creash on start is a bug and therefor needs to be addressed.

**Comment by lewisje** [comment]
Sorry, I wasn't reading closely enough and thought you were talking about setting the font to "System"; the look-and-feel "system" has not used that particular font in any version of Windows that Java runs on.

**Comment by pyro17** [comment]
It's alright, just tried to clarify what I meant there. And yea I agree the font isnt that good ;)
